odom_frame: odom
base_link_frame: base_link
world_frame: odom
map_frame: map

two_d_mode: true

frequency: 50

odom0: imibot_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: true
odom0_queue_size: 50

imu0: imibot/imu_sensor
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true