# Teleop configuration for PS3 Navigation joystick.
teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.1
  scale_linear_turbo: 2.0
  axis_angular: 2
  scale_angular: 0.1
  scale_angular_turbo: 2.0
  enable_button: 8
  enable_turbo_button: 10
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js2